# Generated by Django 6.0.4 on 2026-05-23 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="must_change_password",
            field=models.BooleanField(default=True),
        ),
    ]
