# Generated by Django 6.0.4 on 2026-05-25 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_studentprofile_must_change_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="full_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="profile_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="program",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="year",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
