# Generated by Django 6.0.4 on 2026-06-15 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="program",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="year",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name="StudentProfile",
        ),
    ]
