# Generated by Django 6.0.4 on 2026-06-18 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="edited",
            field=models.BooleanField(default=False),
        ),
    ]
