# Generated by Django 6.0.4 on 2026-06-18 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0002_message_edited"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="edited_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
